name: 'Security Code Scanner'
inputs:
  repo: 
    description: 'Repo to be scanned' 
    required: true
  paths_ignored:
    description: 'Comma delimited paths to ignore during scan' 
    required: false
  rules_excluded:
    description: 'Comma delimited IDs of rules to exclude' 
    required: false
    
runs:
  using: 'composite'
  steps:
    - name: Check out repo to scan
      uses: actions/checkout@v4
      with: 
        repository: ${{ inputs.repo }}
        path: ${{ inputs.repo }}
    - name: CodeQL Scan
      uses: witmicko/CodeQL-action@pre-copy
      with:
        repo: ${{ inputs.repo }}
        paths_ignored: ${{ inputs.paths_ignored }}
        rules_excluded: ${{ inputs.rules_excluded }}
